# Site settings
name: onote2
description: "Software Engineer in Tokyo, Japan."
url: ""


# Delete the lines you don't need
# about 5 elements are recomended
github_username: onote2
codepen_username: 
facebook_username: 
vk_username: 
twitter_username: onote2
google_plus_username: 
linkedin_username: 
vine_username: 
instagram_username:  
flickr_username: 
steam_username: 
soundcloud_username: 
stack_of_username: 
reddit_username: 
medium_username: 
tumblr_username: 
weibo_username: 
lastfm_username: 
blog_url: "https://blog.onote2.com"
email: onote2.jp@gmail.com
public_key_url: 


avatar: yes
avatar_img_path: "imgs/avatar.jpg"
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
#avatar_img_path: "https://avatars2.githubusercontent.com/u/17301305"


front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty

exclude: ['vendor/bundle', 'node_modules', '.git', '.bundle', '.saas-cache', '.bowerrc', '.gitignore', 'Gemfile', 'Gemfile.lock', 'LICENSE', 'README.md', 'CNAME']
